#!/bin/bash
#
#   20110620 Brandon Pierce <brandon@ihashacks.com>
#
#   Verifies that a web server can authentication NTLM
#

#
# Sample Nagios command.cfg definition
# 
#   # 'check_http_ntlm' command definition
#   define command {
#       command_name    check_http_ntlm
#       command_line    $USER1$/check_http_ntlm $ARG1$ $USER3$
#   }

#
# Sample Nagios host entry
#
#   define service {
#       host_name               Server
#       service_description     NTLM Authenticated Web Site
#       is_volatile             0
#       check_period            24x7
#       max_check_attempts      3
#       normal_check_interval   5
#       retry_check_interval    1
#       contact_groups          nagiosadmins
#       notification_interval   120
#       notification_period     24x7
#       notification_options    c,r
#       check_command           check_http_ntlm!https://server.com
#   }

PROG=/usr/bin/curl
HOST=$1
AUTH=$2

$PROG -s -S --ntlm --head -u $AUTH -k $HOST | grep -w 200 > /dev/null

if [ $? -eq 0 ]
  then
    echo "Authentication Success"
     else echo "Authentication Failure"
  exit 2
fi
