#!/bin/bash
#Testing Phase

# Check space on "/"
SIZE=`df -k / | tail -1 | awk '{print $4}'`

if [ $SIZE -lt 1000000 ]; then
   echo '/ on Tarostar Below Low Water. Currently ' $SIZE ' KBytes Remain' | /usr/bin/Mail dba@laguna.sparta.com -s 'Low Disk Space'  
fi

# Check space on "/usr"
SIZE=`df -k /usr | tail -1 | awk '{print $4}'`

if [ $SIZE -lt 3000000 ]; then
   echo '/usr/local on Tarostar Below Low Water. Currently ' $SIZE ' KBytes Remain' | /usr/bin/Mail dba@laguna.sparta.com -s 'Low Disk Space'  
fi

#Check space on "/var"

SIZE=`df -k /var | tail -1 | awk '{print $4}'`

if [ $SIZE -lt 100000 ]; then
   echo '/var on Tarostar Below Low Water. Currently ' $SIZE ' KBytes Remain' | /usr/bin/Mail dba@laguna.sparta.com -s 'Low Disk Space'  
fi
