#!/bin/bash

SSH=/usr/bin/ssh
PROXYPORT=1088
VPNHOST=vpn12.findnot.com
VPNUSER=accessibm

#export PROMPT_COMMAND='echo -ne "\033]0;Findnot\007"'

while true ; do \
	$SSH -v -D $PROXYPORT -p 80 $VPNUSER@$VPNHOST ;
	sleep 10;
done
