#!/bin/bash
#whatismyip.com has address 38.114.169.193
#whatismyip.com has address 38.114.169.197
#whatismyip.com has address 38.114.169.149
#whatismyip.com has address 38.114.169.153
#whatismyip.com has address 38.114.169.189
#whatismyip.com mail is handled by 10 mail.verycurious.com.

/usr/bin/links -dump http://automation.whatismyip.com/n09230945.asp | \
#/usr/bin/links -dump http://content.ihashacks.com:8080/php-lib/ipcheck.php | \
grep -e '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' #| \
#awk ' { print $4 } '
