#!/bin/bash
#
#	20080628	Brandon Pierce <brandon@ihashacks.com>
#

MAC=/usr/share/nmap/nmap-mac-prefixes

usage()
{
	echo "Usage: `basename $0` <mac>"
}


grep `echo $1 | sed -e 's/[:-]//g' | cut -c 1-6` $MAC
if [ $? == 1 ]; then
		echo "MAC not found!";
fi
