#!/bin/bash

################################################################################
#	License
################################################################################
#
#	Copyright (c) 2013 Brandon Pierce <brandon@ihashacks.com>
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

################################################################################
#	Changelog
################################################################################
#
#	Written 20130226 by Brandon Pierce <brandon@ihashacks.com>
#
#       gets juju + LXC ready to go
#

################################################################################
#	Documentation
################################################################################
#
# Lazified version of https://juju.ubuntu.com/docs/getting-started.html
#

apt-get install -y python-software-properties
add-apt-repository ppa:juju/pkgs
apt-get update
apt-get install -y juju
apt-get install -y lxc apt-cacher-ng libzookeeper-java zookeeper

if [ ! -r $HOME/.ssh/id_rsa ]; then
	ssh-keygen -t rsa
fi

mkdir .juju
vim $HOME/.juju/environments.yaml

juju bootstrap
