#!/bin/sh
# Snix (Snort to Pix rules) (c) 2006 
# J. Oquendo
# echo @infiltrated|sed 's/^/sil/g;s/$/.net/g'
# Snort /var/log/snort/alert to Cisco Pix ACL rule

# Generates a rule for your Pix based off of attackers
# logged in Snort

awk -F ":" '/->/{print $3}' /var/log/snort/alert|\
awk '! a[$0]++{print $2 | "sort" }'|\
uniq|\
awk '{print "access-list 102 deny tcp any "$1}'

# Use with caution. If you don't know how rules are
# assembled and you did say a pen-test to the machine
# you're generating your rules for... Guess what Einstein
# you're likely to block yourself...

