#!/usr/bin/expect

send_user "password?\ "
expect_user -re "(.*)\n"
for {} 1 {} {
	if {[fork] !=0} {sleep 1;continue}
	disconnect
	spawn /home/brandon/bin/sshlooptest
	expect Password:
	send "expect_out(1,string)\r"
	exit
}
