#!/bin/bash
#
#	Written 20120315 by Brandon Pierce <brandon@ihashacks.com>
#
#	20120317 - added Adobe Flash support
#

set -x

############################################################
# variables
OUTPUTBASE="/apps/Software"
TMP="/tmp"
#GET="echo wget"
GET="wget -nc"

############################################################
# functions

usage()
{
	echo "Usage: `basename $0`"
}

adobe_acrobat()
{
	echo "Updating Adobe Acrobat Standard..."
}

adobe_flash()
{
	FLASHBASEURL="http://fpdownload.macromedia.com/pub/flashplayer/current/licensing/win"
	FLASHVERFULL=`wget -q -O - https://www.adobe.com/products/flashplayer/distribution3.html | grep -m 1 -o -e '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'`
	FLASHVERMAJOR=`echo $FLASHVERFULL | cut -d \. -f1`
	FLASHOUT="$OUTPUTBASE/Adobe/Flash Player"
	[ -e "$FLASHOUT" ] || mkdir "$FLASHOUT"
	echo "Updating Adobe Flash $FLASHVERMAJOR to version $FLASHVERFULL..."
	$GET -O "$FLASHOUT/install_flash_player_"$FLASHVERFULL"_active_x_32bit.msi" $FLASHBASEURL/install_flash_player_"$FLASHVERMAJOR"_active_x_32bit.msi
	$GET -O "$FLASHOUT/install_flash_player_"$FLASHVERFULL"_active_x_64bit.msi" $FLASHBASEURL/install_flash_player_"$FLASHVERMAJOR"_active_x_64bit.msi
	$GET -O "$FLASHOUT/install_flash_player_"$FLASHVERFULL"_plugin_32bit.msi" $FLASHBASEURL/install_flash_player_"$FLASHVERMAJOR"_plugin_32bit.msi
	$GET -O "$FLASHOUT/install_flash_player_"$FLASHVERFULL"_plugin_64bit.msi" $FLASHBASEURL/install_flash_player_"$FLASHVERMAJOR"_plugin_64bit.msi
	echo
}

adobe_reader()
{
	echo "Updating Adobe Reader..."
}

oracle_java()
{
	echo "Updating Oracle Java..."
}

piriform_ccleaner()
{
	PFBASEURL="http://www.piriform.com"
	CCVERFULL=`wget -q -O - http://www.piriform.com/ccleaner/builds | grep -o -e 'ccsetup[0-9]*\.zip' | grep -o -e '[0-9]*'`
	CCVERMAJOR=`echo $CCVERFULL | cut -c 1`
	CCOUT="$OUTPUTBASE/Piriform/CCleaner"
	[ -e "$CCOUT" ] || mkdir "$CCOUT"
	echo "Updating Piriform CCleaner $CCVERMAJOR to version $CCVERFULL..."
	$GET -O "$TMP/ccsetup"$CCVERFULL".zip" $PFBASEURL/ccleaner/download/portable/downloadfile
	unzip -q $TMP/ccsetup"$CCVERFULL".zip -d "$CCOUT"/ccsetup"$CCVERFULL"
	rm $TMP/ccsetup"$CCVERFULL".zip
	echo
}

piriform_defraggler()
{
	PFBASEURL="http://www.piriform.com"
	DFVERFULL=`wget -q -O - http://www.piriform.com/defraggler/builds | grep -o -e 'dfsetup[0-9]*\.zip' | grep -o -e '[0-9]*'`
	DFVERMAJOR=`echo $DFVERFULL | cut -c 1`
	DFOUT="$OUTPUTBASE/Piriform/Defraggler"
	[ -e "$DFOUT" ] || mkdir "$DFOUT"
	echo "Updating Piriform Defraggler $DFVERMAJOR to version $DFVERFULL..."
	$GET -O "$DFOUT/dfsetup"$DFVERFULL".zip" $PFBASEURL/defraggler/download/portable/downloadfile
	echo
}

sysinternals_suite()
{
	SIBASEURL="http://download.sysinternals.com/files"
	SIOUT="$OUTPUTBASE/Sysinternals"
	[ -e "$SIOUT" ] || mkdir "$SIOUT"
	echo "Updating SysInternals Suite..."
	$GET -O "$SIOUT/SysinternalsSuite.zip" $SIBASEURL/SysinternalsSuite.zip
	echo
}

update_all()
{
        adobe_acrobat
		adobe_flash
		adobe_reader
		oracle_java
		piriform_ccleaner
		piriform_defraggler
		sysinternals_suite
}

adobe_flash
piriform_ccleaner
piriform_defraggler
