#!/bin/bash
#
#	20080626	Brandon Pierce <brandon@ihashacks.com>
#
#		Convenience wrapper for Cisco Systems VPN client
#
#
#	Modifications:
#
#	20080626
#	- Add support for disabling firewall
#

VPNCLI=/usr/local/bin/vpnclient

usage()
{
		echo "Usage: `basename $0` <profile name>"
		exit 1
}


#
#	Sanity checks
#

if [ ${#@} != 1 ] ; then
		usage
fi


#
#	Start VPN service if not already started, make sure to disable
#	your firewall first kids!
#

sudo service firestarter status &>/dev/null && \
	sudo service firestarter stop

service vpnclient_init status &>/dev/null || \
	sudo service vpnclient_init start

service vpnagentd_init status &>/dev/null || \
	sudo service vpnagentd_init start && $VPNCLI connect $1



#
#	Put your toys back where you found them when you're done playing!
#
sudo service vpnclient_init stop
sudo service vpnagentd_init stop
sudo service firestarter start
